CREATE TABLE authors (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         name VARCHAR(100) UNIQUE NOT NULL,
                         created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                         updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE books (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       title VARCHAR(200) NOT NULL,
                       publish_year INT NOT NULL CHECK (publish_year BETWEEN -4000 AND EXTRACT(YEAR FROM CURRENT_DATE)),
                       author_id BIGINT NOT NULL REFERENCES authors(id) ON DELETE RESTRICT,
                       created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                       updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_books_author ON books(author_id);