spring.datasource.url=jdbc:postgresql://localhost:5433/library
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.show-sql=true
logging.level.root=INFO
logging.level.com.example.library=DEBUG